# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: 'a@a.com', password: "12345678")
User.create(email: 'b@b.com', password: "12345678")
User.create(email: 'c@c.com', password: "12345678")

Engine.create(name: 'Shooter', image: "/tests/engine/1.png", description: "Kill and do not die.", license_id: 1)
Engine.create(name: 'Fighter', image: "/tests/engine/2.png", description: "Humilliate your friends.", license_id: 2)
Engine.create(name: 'Visual Novel', image: "/engine/eninge/3.png", description: "Find true love.", license_id: 2)

Game.create(engine_id: 1, name: 'Maximum Overkill', image: '/tests/game/1.png', description: 'War destroyer', license_id: 1)
Game.create(engine_id: 1, name: 'Shaniqua', image: '/tests/game/2.png', description: 'The end is near', license_id: 2)
Game.create(engine_id: 2, name: 'Chan Balam', image: '/tests/game/3.png', description: 'Fight!', license_id: 1)
Game.create(engine_id: 2, name: 'Supah Stick Faitah', image: '/tests/game/4.png', description: 'No scrubs accepted.', license_id: 1)
Game.create(engine_id: 3, name: 'Katawa Shoujo', image: '/tests/game/5.png', description: 'The feels are too strongs.', license_id: 2)

Component.create(engine_id: 1, name: "Final boss: Hard", image: "/tests/component/1.png", description: "such desc", license_id: 1)
Component.create(engine_id: 1, name: "Final boss: Hell", image: "/tests/component/2.png", description: "much wow", license_id: 1)
Component.create(engine_id: 1, name: "Final boss: Lunatic", image: "/tests/component/3.png", description: "very component", license_id: 1)
Component.create(engine_id: 2, name: "Ultimate battlefield", image: "/tests/component/4.png", description: "much battlefield", license_id: 2)
Component.create(engine_id: 4, name: "High school dreams", image: "/tests/component/5.png", description: "amaze", license_id: 2)
Component.create(engine_id: 4, name: "Love scene", image: "/tests/component/6.png", description: "such scene", license_id: 1)

Asset.create(component_id: 1, category_id: 1, name: 'Menu sfx', download: 'this is not set', license_id: 1)
Asset.create(component_id: 1, category_id: 2, name: 'Angry boss sprites', download: 'this is not set', license_id: 1)
Asset.create(component_id: 1, category_id: 2, name: 'Deathful bullets', download: 'this is not set', license_id: 2)
Asset.create(component_id: 2, category_id: 1, name: 'Annoying sound effects', download: 'this is not set', license_id: 2)
Asset.create(component_id: 2, category_id: 3, name: 'Sprites', download: 'this is not set', license_id: 1)
Asset.create(component_id: 3, category_id: 1, name: 'Game music', download: 'this is not set', license_id: 1)
Asset.create(component_id: 4, category_id: 2, name: 'Voices pack', download: 'this is not set', license_id: 2)
Asset.create(component_id: 5, category_id: 1, name: 'XML code', download: 'this is not set', license_id: 1)
Asset.create(component_id: 6, category_id: 1, name: 'Small crying bunny', download: 'this is not set', license_id: 1)

Incentive.create(asset_id: 1, user_id: 1, amount: 100)
Incentive.create(asset_id: 3, user_id: 1, amount: 500)
Incentive.create(asset_id: 3, user_id: 2, amount: 200)
Incentive.create(asset_id: 3, user_id: 4, amount: 1500)

Credit.create(user_id: 1, asset_id: 1)
Credit.create(user_id: 2, asset_id: 1)
Credit.create(user_id: 3, asset_id: 1)
Credit.create(user_id: 2, asset_id: 1)
Credit.create(user_id: 3, asset_id: 2)
Credit.create(user_id: 3, asset_id: 2)
Credit.create(user_id: 1, asset_id: 3)
Credit.create(user_id: 1, asset_id: 4)
Credit.create(user_id: 1, asset_id: 5)
Credit.create(user_id: 1, asset_id: 6)
Credit.create(user_id: 2, asset_id: 6)
Credit.create(user_id: 3, asset_id: 6)

Category.create(name: 'sfx')
Category.create(name: 'graphics')
Category.create(name: 'music')
Category.create(name: 'gameplay')

License.create(name: "GPL", website: "http://www.gnu.org/licenses/gpl.html")
License.create(name: "MIT", website: "http://opensource.org/licenses/MIT")

ComponentInGame.create(component_id: 1, game_id: 1)
ComponentInGame.create(component_id: 2, game_id: 1)
ComponentInGame.create(component_id: 3, game_id: 1)
ComponentInGame.create(component_id: 5, game_id: 2)
ComponentInGame.create(component_id: 5, game_id: 2)

EngineRating.create(engine_id: 1, rating: 3)
EngineRating.create(engine_id: 1, rating: 5)
EngineRating.create(engine_id: 1, rating: 4)
EngineRating.create(engine_id: 2, rating: 5)
EngineRating.create(engine_id: 2, rating: 1)
EngineRating.create(engine_id: 3, rating: 2)

GameRating.create(game_id: 1, rating: 3)
GameRating.create(game_id: 1, rating: 5)
GameRating.create(game_id: 1, rating: 4)
GameRating.create(game_id: 2, rating: 5)
GameRating.create(game_id: 2, rating: 1)
GameRating.create(game_id: 3, rating: 2)

ComponentRating.create(component_id: 1, rating: 3)
ComponentRating.create(component_id: 1, rating: 5)
ComponentRating.create(component_id: 1, rating: 4)
ComponentRating.create(component_id: 2, rating: 5)
ComponentRating.create(component_id: 2, rating: 1)
ComponentRating.create(component_id: 3, rating: 2)

AssetRating.create(asset_id: 1, rating: 3)
AssetRating.create(asset_id: 1, rating: 5)
AssetRating.create(asset_id: 1, rating: 4)
AssetRating.create(asset_id: 2, rating: 5)
AssetRating.create(asset_id: 2, rating: 1)
AssetRating.create(asset_id: 3, rating: 2)

EngineComment.create(engine_id: 1, user_id: 1, comment: "much wow")
EngineComment.create(engine_id: 1, user_id: 2, comment: "such wow")
EngineComment.create(engine_id: 1, user_id: 1, comment: "amaze")
EngineComment.create(engine_id: 2, user_id: 2, comment: "very comment")
EngineComment.create(engine_id: 2, user_id: 2, comment: "much engine")
EngineComment.create(engine_id: 3, user_id: 2, comment: "so wow")

GameComment.create(game_id: 1, user_id: 1, comment: "much wow")
GameComment.create(game_id: 1, user_id: 2, comment: "such wow")
GameComment.create(game_id: 1, user_id: 1, comment: "amaze")
GameComment.create(game_id: 2, user_id: 2, comment: "very comment")
GameComment.create(game_id: 2, user_id: 2, comment: "much engine")
GameComment.create(game_id: 3, user_id: 2, comment: "so wow")

ComponentComment.create(component_id: 1, user_id: 1, comment: "much wow")
ComponentComment.create(component_id: 1, user_id: 2, comment: "such wow")
ComponentComment.create(component_id: 1, user_id: 1, comment: "amaze")
ComponentComment.create(component_id: 2, user_id: 2, comment: "very comment")
ComponentComment.create(component_id: 2, user_id: 2, comment: "much engine")
ComponentComment.create(component_id: 3, user_id: 2, comment: "so wow")

AssetComment.create(asset_id: 1, user_id: 1, comment: "much wow")
AssetComment.create(asset_id: 1, user_id: 2, comment: "such wow")
AssetComment.create(asset_id: 1, user_id: 1, comment: "amaze")
AssetComment.create(asset_id: 2, user_id: 2, comment: "very comment")
AssetComment.create(asset_id: 2, user_id: 2, comment: "much engine")
AssetComment.create(asset_id: 3, user_id: 2, comment: "so wow")

EngineTag.create(engine_id: 1, tag_id: 3)
EngineTag.create(engine_id: 1, tag_id: 5)
EngineTag.create(engine_id: 1, tag_id: 4)
EngineTag.create(engine_id: 2, tag_id: 5)
EngineTag.create(engine_id: 2, tag_id: 1)
EngineTag.create(engine_id: 3, tag_id: 2)

GameTag.create(game_id: 1, tag_id: 3)
GameTag.create(game_id: 1, tag_id: 5)
GameTag.create(game_id: 1, tag_id: 4)
GameTag.create(game_id: 2, tag_id: 5)
GameTag.create(game_id: 2, tag_id: 1)
GameTag.create(game_id: 3, tag_id: 2)

ComponentTag.create(component_id: 1, tag_id: 3)
ComponentTag.create(component_id: 1, tag_id: 5)
ComponentTag.create(component_id: 1, tag_id: 4)
ComponentTag.create(component_id: 2, tag_id: 5)
ComponentTag.create(component_id: 2, tag_id: 1)
ComponentTag.create(component_id: 3, tag_id: 2)

AssetTag.create(asset_id: 1, tag_id: 3)
AssetTag.create(asset_id: 1, tag_id: 5)
AssetTag.create(asset_id: 1, tag_id: 4)
AssetTag.create(asset_id: 2, tag_id: 5)
AssetTag.create(asset_id: 2, tag_id: 1)
AssetTag.create(asset_id: 3, tag_id: 2)

Tag.create(name: "yolo")
Tag.create(name: "swag")
Tag.create(name: "kony2016")
Tag.create(name: "hacelopue")
Tag.create(name: "maiwaifu")
Tag.create(name: "31337")
